Repository spiral/roadrunner-bridge, pull requests merged in 2022-09, with the labels that each got.

#28 Adding the ability to configure priority and autoAck
  src/Queue/Dispatcher.php
  src/Queue/Options.php
  src/Queue/Queue.php
  tests/src/Queue/OptionsTest.php
  tests/src/Queue/QueueTest.php
Labels: Feature

#32 Fixes jobs pipeline stat for console command
  src/Console/Command/Queue/ListCommand.php
  tests/src/Console/Command/Queue/ListCommandTest.php
Labels: bug, Component: Queue

#31 Update gh actions
  .github/workflows/main.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
  .github/workflows/static.yml
  README.md
Labels: documentation, enhancement
