Repository spiral/roadrunner-bridge, pull requests merged in 2022-07, with the labels that each got.

#18 Adds an ability to connect to a pipeline without configuration.
  composer.json
  src/Queue/RPCPipelineRegistry.php
  tests/src/Queue/RPCPipelineRegistryTest.php
Labels: Improvement, Component: Queue

#20 Removing information about callable jobs
  README.md
Labels: documentation

#21 Added RoadRunner metrics support
  README.md
  composer.json
  src/Bootloader/MetricsBootloader.php
  tests/App/App.php
  tests/src/Bootloader/MetricsBootloaderTest.php
Labels: enhancement
